#!/bin/bash

PROJECT="demo-poly-2023-theme-alpha"
echo "Project: $PROJECT" 

LAGOON_KEY=`lagoon get project-key -p $PROJECT | tail -n 1` 
echo $LAGOON_KEY > /tmp/lagoon-polyalphakeypub.aio 
echo "Key: $LAGOON_KEY" 

gh repo deploy-key add /tmp/lagoon-polyalphakeypub.aio
